### ISSUE TITLE
Page build fails

### ISSUE THREAD

**Issue by risteardc** [buildingblocks/bb-prototype-website-razor#15]
When adding new components to a page and saving nothing happens.

To see the component you have added to the page you need to stop the build in terminal and run gulp again.

**Comment by jimmah** [comment]
Could this be related to aspnet/RazorTooling#93 ?

**Comment by jimmah** [comment]
Digging into the code, this looks like its possibly by design: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/DependencyInjection/MvcRazorMvcCoreBuilderExtensions.cs#L167

However, I don't understand why Richie is seeing the views update *except* if they're in the `/Views/Pages` directory.

I think we might just have to wait for [dotnet watch](https://github.com/aspnet/DotNetTools/tree/dev/src/Microsoft.DotNet.Watcher.Tools) to be updated to work with the .csproj build system, which should sort it.
